# Generated by Django 3.2.4 on 2021-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_archivo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
