# Generated by Django 3.2.4 on 2021-10-19 20:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0002_reemplazomercaderia_reemplazomercaderialinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(default='movimientos', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='producto.producto')),
                ('ingreso_linea', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='producto.ingresolinea')),
                ('reemplazo_linea', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reemplazos', to='producto.reemplazomercaderialinea')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('auditoria_creado_fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('auditoria_modificado_fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('auditoria_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('auditoria_modificado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
