# Generated by Django 3.2.4 on 2021-10-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20211013_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='compra_directa',
            field=models.BooleanField(default=True),
        ),
    ]
