# Generated by Django 3.2.4 on 2021-06-13 12:28

from django.db import migrations, models
import django.db.models.deletion
import producto.models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_categoria_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default='productos', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='producto.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='producto/default.jpg', null=True, upload_to=producto.models.upload_to, verbose_name='Image'),
        ),
    ]
