# Generated by Django 3.2.4 on 2021-10-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_compra_directa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresolinea',
            old_name='precio',
            new_name='costo',
        ),
    ]
