# Generated by Django 3.2.4 on 2021-10-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alta_ingresos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(default='movimientos', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='producto.producto'),
        ),
    ]
