# Generated by Django 3.2.4 on 2021-10-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_rename_precio_ingresolinea_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='venta_directa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='compra_directa',
            field=models.BooleanField(default=False),
        ),
    ]
