# Generated by Django 3.2.4 on 2021-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20210613_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_nombre',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
