# Generated by Django 3.2.4 on 2021-06-13 19:17

from django.db import migrations, models
import producto.models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_imagen_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='producto/defecto/default.jpg', null=True, upload_to=producto.models.upload_to, verbose_name='Image'),
        ),
    ]
