# Generated by Django 3.2.4 on 2021-06-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_vigente',
            field=models.FloatField(),
        ),
    ]
