# Generated by Django 3.2.4 on 2021-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_movimientostock_venta_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='reemplazomercaderialinea',
            name='cantidad_egreso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reemplazomercaderialinea',
            name='cantidad_ingreso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
