# Generated by Django 3.2.4 on 2021-07-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_alter_producto_precio_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
