# Generated by Django 3.2.4 on 2022-04-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20211202_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
