# Generated by Django 3.2.4 on 2021-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
