# Generated by Django 3.2.4 on 2022-04-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_producto_codigo_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(default='', max_length=255),
        ),
    ]
