# Generated by Django 3.2.4 on 2021-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_ingreso_ingresolinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresolinea',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresolinea',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresolinea',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
