# Generated by Django 3.2.4 on 2021-10-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_auto_20211006_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresolinea',
            name='subtotal',
        ),
    ]
