# Generated by Django 3.2.4 on 2021-10-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_remove_ingresolinea_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
