# Generated by Django 3.2.4 on 2021-10-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0015_alter_ingreso_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
