# Generated by Django 3.2.4 on 2021-10-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0017_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
