# Generated by Django 3.2.4 on 2021-06-07 02:16

from django.db import migrations


def agregar_roles(apps, schema_editor):
    Rol = apps.get_model('backend', 'Rol')

    root = Rol(nombre="root", legible="Root", descripcion="Rol con todos los permisos.", root=1)
    root.save()

    admin = Rol(nombre="admin", legible="Administrador",
                descripcion="Administrador del sistema. Se encarga del ingreso y creación de usuarios.", root=0)
    admin.save()

    mozo = Rol(nombre="mozo", legible="Mozo", descripcion="Persona que puede gestiona las mesas.", root=0)
    mozo.save()

    comensal = Rol(nombre="comensal", legible="Comensal", descripcion="Usuario que realiza pedidos online.", root=0)
    comensal.save()

    vendedor = Rol(nombre="vendedor", legible="Vendedor", descripcion="Usuario que realiza ventas desde la caja.",
                   root=0)
    vendedor.save()


def borrar_roles(apps, schema_editor):
    Rol = apps.get_model('backend', 'Rol')
    Rol.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(agregar_roles, borrar_roles),
    ]
