# Generated by Django 3.1.7 on 2021-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_token_reset',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_email',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_reset',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
