# Generated by Django 3.1.7 on 2021-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210605_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='usuarios_roles', to='backend.Rol'),
        ),
    ]
