# Generated by Django 3.2.4 on 2021-06-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210608_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
