# Generated by Django 3.2.4 on 2021-06-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210605_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios_roles', to='backend.Rol'),
        ),
    ]
