# Generated by Django 3.2.4 on 2021-06-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
