# Generated by Django 3.2.4 on 2021-06-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_usuario_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_reset',
            field=models.TextField(null=True),
        ),
    ]
