# Generated by Django 3.2.4 on 2021-06-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbo_soft', '0006_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
