# Generated by Django 3.2.4 on 2021-07-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbo_soft', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
