# Generated by Django 3.2.4 on 2021-07-25 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jumbo_soft.models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbo_soft', '0008_usuario_borrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditoria_creado_fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('auditoria_modificado_fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('auditoria_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('auditoria_modificado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inferiores', to='jumbo_soft.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditoria_creado_fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('auditoria_modificado_fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(default='producto/defecto/default.jpg', null=True, upload_to=jumbo_soft.models.upload_to, verbose_name='Image')),
                ('imagen_nombre', models.CharField(default='default.jpg', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=255)),
                ('precio_vigente', models.FloatField()),
                ('habilitado', models.BooleanField(default=True)),
                ('borrado', models.BooleanField(default=False)),
                ('auditoria_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('auditoria_modificado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(default='productos', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='jumbo_soft.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
