# Generated by Django 3.2.4 on 2021-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
