# Generated by Django 3.2.4 on 2021-06-09 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210606_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='auditoria_creado_fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='auditoria_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='auditoria_modificado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='auditoria_modificado_fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
