# Generated by Django 3.2.4 on 2021-10-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_usuario_borrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
