# Generated by Django 3.2.4 on 2021-06-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='auditoria_creado_fecha',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='auditoria_creador',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='auditoria_modificado',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='auditoria_modificado_fecha',
        ),
        migrations.RemoveField(
            model_name='pedidolinea',
            name='auditoria_creado_fecha',
        ),
        migrations.RemoveField(
            model_name='pedidolinea',
            name='auditoria_creador',
        ),
        migrations.RemoveField(
            model_name='pedidolinea',
            name='auditoria_modificado',
        ),
        migrations.RemoveField(
            model_name='pedidolinea',
            name='auditoria_modificado_fecha',
        ),
    ]
