# Generated by Django 3.2.4 on 2021-06-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_alter_producto_precio_vigente'),
        ('gastronomia', '0002_auto_20210614_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidolinea',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='producto.producto'),
        ),
    ]
