# Generated by Django 3.2.4 on 2021-11-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0003_venta_ventalinea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gastronomia.venta'),
        ),
    ]
