# Generated by Django 3.2.4 on 2021-07-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0003_alter_pedidolinea_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidolinea',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='gastronomia.pedido'),
        ),
    ]
