# Generated by Django 3.2.4 on 2021-07-06 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0004_alter_pedidolinea_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='gastronomia.pedido'),
        ),
    ]
