# Generated by Django 3.2.4 on 2021-11-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_ordenproducto_turno'),
        ('gastronomia', '0004_auto_20211120_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gastronomia.pedido'),
        ),
        migrations.AddField(
            model_name='venta',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mesas.turno'),
        ),
    ]
