# Generated by Django 3.2.4 on 2021-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0005_auto_20211121_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cambio',
            field=models.FloatField(default=0),
        ),
    ]
