# Generated by Django 3.2.4 on 2021-07-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_categoria_descripcion'),
        ('gastronomia', '0005_alter_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidolinea',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='producto.producto'),
        ),
    ]
