# Generated by Django 3.2.4 on 2021-12-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0005_auto_20211121_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cambio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(blank=True, default='retiro', max_length=30),
        ),
    ]
