# Generated by Django 3.2.4 on 2021-09-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0006_alter_pedidolinea_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(default='online', max_length=15),
            preserve_default=False,
        ),
    ]
