# Generated by Django 3.2.4 on 2021-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_ordenproducto_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='venta_impresa',
            field=models.BooleanField(default=False),
        ),
    ]
