# Generated by Django 3.2.4 on 2021-12-11 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mesas', '0003_turno_venta_impresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='mozo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
